
import java.awt.Container;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Objects;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 650-079385
 */
public class HangmanGUI extends javax.swing.JFrame 
{
    //Hangman mainClass = new Hangman();
    pickWord pickword = new pickWord();
    Match match = new Match();
    Hangman name = new Hangman();
    private int tries;
    private int score;
    
    public int gettriesNum() 
    {
        //return tries;
        return Integer.valueOf(triesNum.getText());
        //return Integer.parseInt(triesNum.getText());
    }
    public void settriesNum(int tries)
    {
        this.tries = tries;
        this.triesNum.setText(String.valueOf(tries));
    }
    
    public int getScore() 
    {
        return Integer.valueOf(scoreFld.getText());
    }
    public void setScore(int score)
    {
        this.score = score;
        this.scoreFld.setText(String.valueOf(score));
    }
    
    public HangmanGUI()
    {
        initComponents();
        Seticon();
        jPanel2.setVisible(false);
        jPanel6.setVisible(false);
        /*
        S6.setVisible(false);
        S5.setVisible(false);
        S4.setVisible(false);
        S3.setVisible(false);
        S2.setVisible(false);*/
        //tries = 6;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        guess = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nameLbl = new javax.swing.JLabel();
        scoreLbl = new javax.swing.JLabel();
        nameFld = new javax.swing.JLabel();
        scoreFld = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        triesLbl = new javax.swing.JLabel();
        triesNum = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Q = new java.awt.Button();
        W = new java.awt.Button();
        E = new java.awt.Button();
        R = new java.awt.Button();
        T = new java.awt.Button();
        Y = new java.awt.Button();
        U = new java.awt.Button();
        I = new java.awt.Button();
        O = new java.awt.Button();
        P = new java.awt.Button();
        A = new java.awt.Button();
        S = new java.awt.Button();
        D = new java.awt.Button();
        F = new java.awt.Button();
        G = new java.awt.Button();
        H = new java.awt.Button();
        J = new java.awt.Button();
        K = new java.awt.Button();
        L = new java.awt.Button();
        Z = new java.awt.Button();
        X = new java.awt.Button();
        C = new java.awt.Button();
        V = new java.awt.Button();
        B = new java.awt.Button();
        N = new java.awt.Button();
        M = new java.awt.Button();
        jPanel6 = new javax.swing.JPanel();
        next = new java.awt.Button();
        work = new java.awt.Button();
        P6 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        start = new javax.swing.JMenuItem();
        stop = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hangman");
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 600));

        jLayeredPane1.setMinimumSize(new java.awt.Dimension(1024, 557));

        jPanel1.setLayout(null);

        jPanel4.setOpaque(false);

        guess.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        guess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guess, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(guess, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(520, 230, 360, 40);

        jPanel3.setOpaque(false);

        nameLbl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(149, 128, 71));
        nameLbl.setText("Name :");

        scoreLbl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        scoreLbl.setForeground(new java.awt.Color(149, 128, 71));
        scoreLbl.setText("Score :");

        nameFld.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        nameFld.setForeground(new java.awt.Color(149, 128, 71));

        scoreFld.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        scoreFld.setForeground(new java.awt.Color(149, 128, 71));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(scoreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scoreFld, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scoreFld, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 60, 430, 100);

        jPanel5.setOpaque(false);

        triesLbl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        triesLbl.setForeground(new java.awt.Color(149, 128, 71));
        triesLbl.setText("Tries Left :");

        triesNum.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        triesNum.setForeground(new java.awt.Color(149, 128, 71));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(triesLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(triesNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(triesLbl)
                    .addComponent(triesNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(630, 160, 140, 40);
        jPanel5.getAccessibleContext().setAccessibleName("");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 0));

        Q.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Q.setLabel("Q");
        Q.setMinimumSize(new java.awt.Dimension(25, 25));
        Q.setPreferredSize(new java.awt.Dimension(30, 30));
        Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QActionPerformed(evt);
            }
        });

        W.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        W.setLabel("W");
        W.setMinimumSize(new java.awt.Dimension(25, 25));
        W.setPreferredSize(new java.awt.Dimension(30, 30));
        W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WActionPerformed(evt);
            }
        });

        E.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        E.setLabel("E");
        E.setMinimumSize(new java.awt.Dimension(25, 25));
        E.setPreferredSize(new java.awt.Dimension(30, 30));
        E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EActionPerformed(evt);
            }
        });

        R.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        R.setLabel("R");
        R.setMinimumSize(new java.awt.Dimension(25, 25));
        R.setPreferredSize(new java.awt.Dimension(30, 30));
        R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RActionPerformed(evt);
            }
        });

        T.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T.setLabel("T");
        T.setMinimumSize(new java.awt.Dimension(25, 25));
        T.setPreferredSize(new java.awt.Dimension(30, 30));
        T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TActionPerformed(evt);
            }
        });

        Y.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Y.setLabel("Y");
        Y.setMinimumSize(new java.awt.Dimension(25, 25));
        Y.setPreferredSize(new java.awt.Dimension(30, 30));
        Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YActionPerformed(evt);
            }
        });

        U.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        U.setLabel("U");
        U.setMinimumSize(new java.awt.Dimension(25, 25));
        U.setPreferredSize(new java.awt.Dimension(30, 30));
        U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UActionPerformed(evt);
            }
        });

        I.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        I.setLabel("I");
        I.setMinimumSize(new java.awt.Dimension(25, 25));
        I.setPreferredSize(new java.awt.Dimension(30, 30));
        I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IActionPerformed(evt);
            }
        });

        O.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        O.setLabel("O");
        O.setMinimumSize(new java.awt.Dimension(25, 25));
        O.setPreferredSize(new java.awt.Dimension(30, 30));
        O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OActionPerformed(evt);
            }
        });

        P.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        P.setLabel("P");
        P.setMinimumSize(new java.awt.Dimension(25, 25));
        P.setPreferredSize(new java.awt.Dimension(30, 30));
        P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PActionPerformed(evt);
            }
        });

        A.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        A.setLabel("A");
        A.setMinimumSize(new java.awt.Dimension(25, 25));
        A.setPreferredSize(new java.awt.Dimension(30, 30));
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });

        S.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        S.setLabel("S");
        S.setMinimumSize(new java.awt.Dimension(25, 25));
        S.setPreferredSize(new java.awt.Dimension(30, 30));
        S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SActionPerformed(evt);
            }
        });

        D.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        D.setLabel("D");
        D.setMinimumSize(new java.awt.Dimension(25, 25));
        D.setPreferredSize(new java.awt.Dimension(30, 30));
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });

        F.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        F.setLabel("F");
        F.setMinimumSize(new java.awt.Dimension(25, 25));
        F.setPreferredSize(new java.awt.Dimension(30, 30));
        F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FActionPerformed(evt);
            }
        });

        G.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        G.setLabel("G");
        G.setMinimumSize(new java.awt.Dimension(25, 25));
        G.setPreferredSize(new java.awt.Dimension(30, 30));
        G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GActionPerformed(evt);
            }
        });

        H.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        H.setLabel("H");
        H.setMinimumSize(new java.awt.Dimension(25, 25));
        H.setPreferredSize(new java.awt.Dimension(30, 30));
        H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HActionPerformed(evt);
            }
        });

        J.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        J.setLabel("J");
        J.setMinimumSize(new java.awt.Dimension(25, 25));
        J.setPreferredSize(new java.awt.Dimension(30, 30));
        J.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JActionPerformed(evt);
            }
        });

        K.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        K.setLabel("K");
        K.setMinimumSize(new java.awt.Dimension(25, 25));
        K.setPreferredSize(new java.awt.Dimension(30, 30));
        K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KActionPerformed(evt);
            }
        });

        L.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        L.setLabel("L");
        L.setMinimumSize(new java.awt.Dimension(25, 25));
        L.setPreferredSize(new java.awt.Dimension(30, 30));
        L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LActionPerformed(evt);
            }
        });

        Z.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Z.setLabel("Z");
        Z.setMinimumSize(new java.awt.Dimension(25, 25));
        Z.setPreferredSize(new java.awt.Dimension(30, 30));
        Z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZActionPerformed(evt);
            }
        });

        X.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        X.setLabel("X");
        X.setMinimumSize(new java.awt.Dimension(25, 25));
        X.setPreferredSize(new java.awt.Dimension(30, 30));
        X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XActionPerformed(evt);
            }
        });

        C.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        C.setLabel("C");
        C.setMinimumSize(new java.awt.Dimension(25, 25));
        C.setPreferredSize(new java.awt.Dimension(30, 30));
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });

        V.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        V.setLabel("V");
        V.setMinimumSize(new java.awt.Dimension(25, 25));
        V.setPreferredSize(new java.awt.Dimension(30, 30));
        V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VActionPerformed(evt);
            }
        });

        B.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B.setLabel("B");
        B.setMinimumSize(new java.awt.Dimension(25, 25));
        B.setPreferredSize(new java.awt.Dimension(30, 30));
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });

        N.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        N.setLabel("N");
        N.setMinimumSize(new java.awt.Dimension(25, 25));
        N.setPreferredSize(new java.awt.Dimension(30, 30));
        N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NActionPerformed(evt);
            }
        });

        M.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        M.setLabel("M");
        M.setMinimumSize(new java.awt.Dimension(25, 25));
        M.setPreferredSize(new java.awt.Dimension(30, 30));
        M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Q, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(W, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(U, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(I, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(O, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(V, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(J, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(K, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addComponent(L, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Q, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(W, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(U, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(I, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(O, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(J, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(K, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(V, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(520, 280, 360, 130);

        jPanel6.setOpaque(false);

        next.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        next.setForeground(new java.awt.Color(149, 128, 71));
        next.setLabel("Next Word");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(520, 280, 360, 130);

        work.setLabel("button1");
        work.setVisible(false);
        work.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workActionPerformed(evt);
            }
        });
        jPanel1.add(work);
        work.setBounds(610, 470, 57, 24);
        jPanel1.add(P6);
        P6.setBounds(0, 200, 440, 360);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scene-201-and-203-anubis-panic-close-up.jpg"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 1024, 576);

        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(102, 102, 102));
        jMenuBar1.setAlignmentX(0.0F);
        jMenuBar1.setMinimumSize(new java.awt.Dimension(72, 25));
        jMenuBar1.setName(""); // NOI18N
        jMenuBar1.setOpaque(false);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(72, 25));

        jMenu1.setText("Game");
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jMenu1.setIconTextGap(18);
        jMenu1.setMargin(new java.awt.Insets(0, 5, 0, 0));
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        start.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        start.setLabel("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        jMenu1.add(start);

        stop.setText("Stop");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        jMenu1.add(stop);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenu2.setIconTextGap(24);
        jMenu2.setMargin(new java.awt.Insets(0, 10, 0, 0));

        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        jMenu2.add(about);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        nameFld.setText(name.name());
        start();
    }//GEN-LAST:event_startActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stopActionPerformed

    private void QActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'q'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_QActionPerformed

    private void XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'x'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_XActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'a'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_AActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        //Runtime.getRuntime().exit(0);
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void JActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'j'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_JActionPerformed

    private void VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'v'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_VActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        pickword.guessWord();
        guess.setText(pickword.getUnderscore().toString());
        jPanel6.setVisible(false);
        jPanel2.setVisible(true);
        settriesNum(5);
        changer();
    }//GEN-LAST:event_nextActionPerformed

    private void WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'w'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_WActionPerformed

    private void EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'e'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_EActionPerformed

    private void RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'r'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_RActionPerformed

    private void TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 't'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_TActionPerformed

    private void YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'y'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_YActionPerformed

    private void UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'u'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_UActionPerformed

    private void IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'i'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_IActionPerformed

    private void OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'o'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_OActionPerformed

    private void PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'p'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_PActionPerformed

    private void SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 's'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_SActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'd'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_DActionPerformed

    private void FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'f'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_FActionPerformed

    private void GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'g'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_GActionPerformed

    private void HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'h'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_HActionPerformed

    private void KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'k'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_KActionPerformed

    private void LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'l'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_LActionPerformed

    private void ZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'z'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_ZActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'c'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_CActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'b'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_BActionPerformed

    private void NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'n'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_NActionPerformed

    private void MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MActionPerformed
        guess.setText(match.show(pickword.getGuess(), pickword.getUnderstring(), 'm'));
        pickword.setUnderString(guess.getText());
        run();
    }//GEN-LAST:event_MActionPerformed

    private void workActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workActionPerformed
        jPanel2.setVisible(false);
        jPanel6.setVisible(true);
    }//GEN-LAST:event_workActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        about();
    }//GEN-LAST:event_aboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HangmanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HangmanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HangmanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HangmanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() {
                new HangmanGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button A;
    private java.awt.Button B;
    private java.awt.Button C;
    private java.awt.Button D;
    private java.awt.Button E;
    private java.awt.Button F;
    private java.awt.Button G;
    private java.awt.Button H;
    private java.awt.Button I;
    private java.awt.Button J;
    private java.awt.Button K;
    private java.awt.Button L;
    private java.awt.Button M;
    private java.awt.Button N;
    private java.awt.Button O;
    private java.awt.Button P;
    private javax.swing.JLabel P6;
    private java.awt.Button Q;
    private java.awt.Button R;
    private java.awt.Button S;
    private java.awt.Button T;
    private java.awt.Button U;
    private java.awt.Button V;
    private java.awt.Button W;
    private java.awt.Button X;
    private java.awt.Button Y;
    private java.awt.Button Z;
    private javax.swing.JMenuItem about;
    private javax.swing.JLabel background;
    private javax.swing.JMenuItem exit;
    private javax.swing.JLabel guess;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel nameFld;
    private javax.swing.JLabel nameLbl;
    private java.awt.Button next;
    private javax.swing.JLabel scoreFld;
    private javax.swing.JLabel scoreLbl;
    private javax.swing.JMenuItem start;
    private javax.swing.JMenuItem stop;
    private javax.swing.JLabel triesLbl;
    private javax.swing.JLabel triesNum;
    private java.awt.Button work;
    // End of variables declaration//GEN-END:variables

    private void Seticon() 
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("h0-mod.png")));
    }
    
    private void reset()
    {
        System.out.println(pickword.getGuess());
        System.out.println(guess.getText());
        
        if(pickword.getGuess().equals(guess.getText()))
        {
            System.out.println("reset");
            jPanel2.setVisible(false);
            jPanel6.setVisible(true);
        }
        else
        {
            System.out.println("no");
        }
    }
    
    private void addCloseWindowListener()
    {
        // NOTE: Must be DO_NOTHING_ON_CLOSE for prompt to function correctly
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
        addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowClosing(WindowEvent we)
            {
                int prompt = JOptionPane.showConfirmDialog(null,
                        "Are you sure you want to quit?",
                        "Quit?", 
                        JOptionPane.YES_NO_OPTION);
                
                if (prompt == JOptionPane.YES_OPTION)
                    System.exit(0);
            }
        });
    }
    
    public void changer()
    {
        if(gettriesNum() == 0)
        {
            String imagePath = "src/h" + gettriesNum() + ".png";
            ImageIcon img ;
            img = new ImageIcon(imagePath);
            P6.setIcon(img);
        
            JOptionPane.showMessageDialog(new JFrame(),
            "<html>Game Over. <br> Your score is: <span style=\"color: red;\">" + match.score + "</span><br>The word is: <span style=\"color: red;\">" + pickword.getGuess().toString().replaceAll("\\s","") + "</span>",
            "Game Over",
            JOptionPane.DEFAULT_OPTION);
            start();
        }
        else
        {
            String imagePath = "src/h" + gettriesNum() + ".png";
            ImageIcon img ;
            img = new ImageIcon(imagePath);
            P6.setIcon(img);
        }
    }

    public void labels()
    {
        triesNum.setText(String.valueOf(match.attempts));
        scoreFld.setText(String.valueOf(match.score));
    }

    public void run()
    {
        reset();
        labels();
        changer();
    }
    public void start()
    {
        pickword.guessWord();
        guess.setText(pickword.getUnderscore().toString());
        match.attempts = 5;
        triesNum.setText(String.valueOf(match.attempts));
        jPanel2.setVisible(true);
        setScore(0);
        match.score = 0;
        changer();
    }
    
    public void about()
    {
        JOptionPane.showMessageDialog(new JFrame(),
        "<html>This game is programmed and designed by <span style=\"color: #2B547E;\"><b>George Saoude</b></span>",
        "About",
        JOptionPane.DEFAULT_OPTION);
    }

}
